Project2/p2/force-app/main/default/objects/Current_Weather__c/Current_Weather__c.object-meta.xml
<CustomObject>
    <label>Current Weather</label>
    <nameField>
        <displayFormat>CW-{0000000000}</displayFormat>
        <label>Current Weather Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Current Weather</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/p2/force-app/main/default/objects/Current_Weather__c/fields/Air_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Air_Pressure__c</fullName>
    <label>Air Pressure</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Current_Weather__c/fields/Heat_Index__c.field-meta.xml
<CustomField>
    <fullName>Heat_Index__c</fullName>
    <label>Heat Index</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Current_Weather__c/fields/Hourly_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Forecast__c</fullName>
    <label>24 Hour Forecast</label>
    <referenceTo>Hourly_Forecast__c</referenceTo>
    <relationshipLabel>Current Weather</relationshipLabel>
    <relationshipName>Current_Weather</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Current_Weather__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Current_Weather__c/fields/Sunrise__c.field-meta.xml
<CustomField>
    <fullName>Sunrise__c</fullName>
    <label>Sunrise</label>
    <type>Time</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Current_Weather__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Current_Weather__c/fields/Wind_Chill__c.field-meta.xml
<CustomField>
    <fullName>Wind_Chill__c</fullName>
    <label>Wind Chill</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Current_Weather__c/fields/Wind_Gust__c.field-meta.xml
<CustomField>
    <fullName>Wind_Gust__c</fullName>
    <label>Wind Gust</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Current_Weather__c/fields/Wind_Heading__c.field-meta.xml
<CustomField>
    <fullName>Wind_Heading__c</fullName>
    <label>Wind Heading</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Current_Weather__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <label>Wind Speed</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/Forecast_Entry__c.object-meta.xml
<CustomObject>
    <description>This object holds all of the information retrieved by a call to the weather API</description>
    <label>Forecast Entry</label>
    <nameField>
        <displayFormat>FC-{00000}</displayFormat>
        <label>Forecast Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Air_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Air_Pressure__c</fullName>
    <label>Air Pressure</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Amount_of_Precipitation__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Precipitation__c</fullName>
    <label>Amount of Precipitation</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Chance_of_Precipitation__c.field-meta.xml
<CustomField>
    <fullName>Chance_of_Precipitation__c</fullName>
    <label>Chance of Precipitation</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Cloud_Cover__c.field-meta.xml
<CustomField>
    <fullName>Cloud_Cover__c</fullName>
    <label>Cloud Cover</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Conditions__c.field-meta.xml
<CustomField>
    <fullName>Conditions__c</fullName>
    <label>Conditions</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date that this forecast was made for</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Hourly_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Forecast__c</fullName>
    <label>24 Hour Forecast</label>
    <referenceTo>Hourly_Forecast__c</referenceTo>
    <relationshipLabel>Forecast</relationshipLabel>
    <relationshipName>Forecast</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Snow_Depth__c.field-meta.xml
<CustomField>
    <fullName>Snow_Depth__c</fullName>
    <label>Snow Depth</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Wind_Gusts__c.field-meta.xml
<CustomField>
    <fullName>Wind_Gusts__c</fullName>
    <label>Wind Gusts</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Wind_Heading__c.field-meta.xml
<CustomField>
    <fullName>Wind_Heading__c</fullName>
    <label>Wind Heading</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <label>Wind Speed</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Hourly_Forecast__c/Hourly_Forecast__c.object-meta.xml
<CustomObject>
    <label>24 Hour Forecast</label>
    <nameField>
        <displayFormat>24HF-{0000000000}</displayFormat>
        <label>24 Hour Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>24 Hour Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/p2/force-app/main/default/objects/Hourly_Forecast__c/fields/Sunset__c.field-meta.xml
<CustomField>
    <fullName>Sunset__c</fullName>
    <label>Sunset</label>
    <type>Time</type>
</CustomField>

Project2/p2/force-app/main/default/classes/Utilities.cls
public class Utilities {
    public static Forecast_Entry__c convertToEntry(Hourly_Forecast__c hFore,
                                                   WeatherDataResponse.HourlyCondition hCon){
        return new Forecast_Entry__c(
            Hourly_Forecast__c = hFore.Id,
            Air_Pressure__c = hCon.sealevelpressure,
            Amount_of_Precipitation__c = hCon.precip,
            Chance_of_Precipitation__c = hCon.pop,
            Cloud_Cover__c = hCon.cloudcover,
            Conditions__c = hCon.conditions,
            Date__c = cleanDateTime(hCon.datetimeStr).date(),
            Heat_Index__c = hCon.heatindex,
            Humidity__c = hCon.humidity,
            Snow_Depth__c = hCon.snowdepth,
            Temperature__c = hCon.temp,
            Time__c = cleanDateTime(hCon.datetimeStr).time(),
            Wind_Chill__c = hCon.windchill,
            Wind_Gusts__c = hCon.wgust,
            Wind_Heading__c = hCon.wdir,
            Wind_Speed__c = hCon.wspd		 
        );
	}

    public static Current_Weather__c convertToCurrentWeather(Hourly_Forecast__c hFore,
                                                   WeatherDataResponse.currentConditions cCon){
        return new Current_Weather__c(
            Hourly_Forecast__c = hFore.Id,
            Air_Pressure__c = cCon.sealevelpressure,
            Amount_of_Precipitation__c = cCon.precip,
            Cloud_Cover__c = cCon.cloudcover,
            Sunrise__c = cleanDateTime(cCon.sunrise).time(),
            Sunset__c = cleanDateTime(cCon.sunset).time(),
            Heat_Index__c = cCon.heatindex,
            Humidity__c = cCon.humidity,
            Snow_Depth__c = cCon.snowdepth,
            Temperature__c = cCon.temp,
            Wind_Chill__c = cCon.windchill,
            Wind_Gust__c = cCon.wgust,
            Wind_Heading__c = cCon.wdir,
            Wind_Speed__c = cCon.wspd		 
        );
	}    
    public static DateTime cleanDateTime(String input){
        //This is the incoming format which is where this monster Regex is coming from
        //"2020-06-28T05:14:26-07:00"
        //System.debug(input);
        Pattern p = Pattern.compile('(\\d{4})-(\\d{2})-(\\d{2})T(\\d{2}):(\\d{2}):(\\d{2})(-?\\d{2}):\\d{2}');
        Matcher pm = p.matcher(input);
        DateTime output;
        if( pm.matches() ){
            Integer year = Integer.valueOf(pm.group(1));
            Integer month = Integer.valueOf(pm.group(2));
            Integer day = Integer.valueOf(pm.group(3));
            Integer hour = Integer.valueOf(pm.group(4));
            //System.debug(pm.group(4));
            Integer minute = Integer.valueOf(pm.group(5));
            Integer second = Integer.valueOf(pm.group(6));
            Integer difference = Integer.valueOf(pm.group(7));
            output = DateTime.newInstanceGmt(year, month, day, hour - difference, minute, second);
        }
        //Mar 8 - Nov 1
        //DST is a thing -_-
        DateTime dstStart = DateTime.newInstance(Date.today().year(), 3, 8);
        DateTime dstEnd = DateTime.newInstance(Date.today().year(), 11, 1);
        Integer dstModifier = 0;
        //if(output>dstStart && output<dstEnd) dstModifier=1;
        //System.debug(output);
        return output;
    }
}