Project2/p2/force-app/main/default/objects/Forecast_Entry__c/Forecast_Entry__c.object-meta.xml
<CustomObject>
    <description>This object holds all of the information retrieved by a call to the weather API</description>
    <label>Forecast Entry</label>
    <nameField>
        <displayFormat>FC-{00000}</displayFormat>
        <label>Forecast Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Air_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Air_Pressure__c</fullName>
    <label>Air Pressure</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Amount_of_Precipitation__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Precipitation__c</fullName>
    <label>Amount of Precipitation</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Chance_of_Precipitation__c.field-meta.xml
<CustomField>
    <fullName>Chance_of_Precipitation__c</fullName>
    <label>Chance of Precipitation</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Cloud_Cover__c.field-meta.xml
<CustomField>
    <fullName>Cloud_Cover__c</fullName>
    <label>Cloud Cover</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Conditions__c.field-meta.xml
<CustomField>
    <fullName>Conditions__c</fullName>
    <label>Conditions</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date that this forecast was made for</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Hourly_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Forecast__c</fullName>
    <label>24 Hour Forecast</label>
    <referenceTo>Hourly_Forecast__c</referenceTo>
    <relationshipLabel>Forecast</relationshipLabel>
    <relationshipName>Forecast</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Where is this forecast entry from?</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Forecast</relationshipLabel>
    <relationshipName>Forecast</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Snow_Depth__c.field-meta.xml
<CustomField>
    <fullName>Snow_Depth__c</fullName>
    <label>Snow Depth</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Wind_Gusts__c.field-meta.xml
<CustomField>
    <fullName>Wind_Gusts__c</fullName>
    <label>Wind Gusts</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Wind_Heading__c.field-meta.xml
<CustomField>
    <fullName>Wind_Heading__c</fullName>
    <label>Wind Heading</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <label>Wind Speed</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Hourly_Forecast__c/Hourly_Forecast__c.object-meta.xml
<CustomObject>
    <label>24 Hour Forecast</label>
    <nameField>
        <displayFormat>24HF-{0000000000}</displayFormat>
        <label>24 Hour Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>24 Hour Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/p2/force-app/main/default/objects/Hourly_Forecast__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>24 Hour Forecasts</relationshipLabel>
    <relationshipName>Hourly_Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Hourly_Forecast__c/fields/Sunset__c.field-meta.xml
<CustomField>
    <fullName>Sunset__c</fullName>
    <label>Sunset</label>
    <type>Time</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Hourly_Forecast__c/fields/Temperature_High__c.field-meta.xml
<CustomField>
    <fullName>Temperature_High__c</fullName>
    <label>Temperature High</label>
    <summarizedField>Forecast_Entry__c.Temperature__c</summarizedField>
    <summaryForeignKey>Forecast_Entry__c.Hourly_Forecast__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Hourly_Forecast__c/fields/Temperature_Low__c.field-meta.xml
<CustomField>
    <fullName>Temperature_Low__c</fullName>
    <label>Temperature Low</label>
    <summarizedField>Forecast_Entry__c.Temperature__c</summarizedField>
    <summaryForeignKey>Forecast_Entry__c.Hourly_Forecast__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>A specific place to reference from forecasts</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project2/p2/force-app/main/default/classes/LocationSearchController.cls
public class LocationSearchController {
    
	@auraEnabled
    public static Hourly_Forecast__c[] getAllHourlies(String city,String state,String country){
        System.debug(city);
        System.debug(state);
        System.debug(country);
        WeatherCallout.fetchCurrentData(city,state,country,false);
        
        //This is... a bit of a beast. It's mostly just because I have long field names though.
        //It's just a query for the 24 forecasts and all of their details including their related children.
        return [SELECT Chance_of_Precipitation__c,Date__c,Location__c,Sunrise__c,Sunset__c,
                               Temperature_High__c,Temperature_Low__c,
                                   (SELECT Temperature__c,Hourly_Forecast__c,Air_Pressure__c,Amount_of_Precipitation__c,
                                   Chance_of_Precipitation__c,Cloud_Cover__c,Conditions__c,Date__c,Heat_Index__c,
                                   Humidity__c, Snow_Depth__c, Time__c, Wind_Chill__c, Wind_Gusts__c, Wind_Heading__c, 
                                   Wind_Speed__c FROM Forecast__r) 
                               FROM Hourly_Forecast__c];
    }
}
//The original SOQL. Just in case.
/*Object[] returnList = [SELECT Temperature__c,Hourly_Forecast__c,Air_Pressure__c,Amount_of_Precipitation__c,
    Chance_of_Precipitation__c,Cloud_Cover__c,Conditions__c,Date__c,Heat_Index__c,
    Humidity__c, Snow_Depth__c, Time__c, Wind_Chill__c, Wind_Gusts__c, Wind_Heading__c, 
    Wind_Speed__c FROM Forecast_Entry__c];
returnList.add();*/