Project2/p2/force-app/main/default/objects/Forecast_Entry__c/Forecast_Entry__c.object-meta.xml
<CustomObject>
    <description>This object holds all of the information retrieved by a call to the weather API</description>
    <label>Forecast Entry</label>
    <nameField>
        <displayFormat>FC-{00000}</displayFormat>
        <label>Forecast Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Air_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Air_Pressure__c</fullName>
    <label>Air Pressure</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date that this forecast was made for</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Feels_Like__c.field-meta.xml
<CustomField>
    <fullName>Feels_Like__c</fullName>
    <label>Feels Like</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/High__c.field-meta.xml
<CustomField>
    <fullName>High__c</fullName>
    <label>High</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Where is this forecast entry from?</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Forecast</relationshipLabel>
    <relationshipName>Forecast</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Low__c.field-meta.xml
<CustomField>
    <fullName>Low__c</fullName>
    <label>Low</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Wind_Heading__c.field-meta.xml
<CustomField>
    <fullName>Wind_Heading__c</fullName>
    <label>Wind Heading</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Forecast_Entry__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <label>Wind Speed</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project2/p2/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>A specific place to reference from forecasts</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project2/p2/force-app/main/default/classes/CurrentConditions.cls
public class CurrentConditions {
	
	public String conditions {get;set;}
	public Decimal visibility {get;set;}
	public Decimal dew {get;set;}
	public DateTime sunrise {get;set;}
	public DateTime sunset {get;set;}
	public Integer wdir {get;set;}
	public Decimal temp {get;set;}
	public Decimal wspd {get;set;}
	public String datetimeStr {get;set;}
	public Decimal cloudcover {get;set;}
	public Decimal heatindex {get;set;}
	public Integer pop {get;set;}
	public Decimal precip {get;set;}
	public Decimal sealevelpressure {get;set;}
	public Decimal snowdepth {get;set;}
	public Decimal humidity {get;set;}
	public Decimal wgust {get;set;}
	public Decimal windchill {get;set;}

	public CurrentConditions(JSONParser parser){
		while (parser.nextToken() != System.JSONToken.END_OBJECT) {
			if (parser.getCurrentToken() == System.JSONToken.FIELD_NAME) {
				String fieldName = parser.getText();
				if (parser.nextToken() != System.JSONToken.VALUE_NULL) {
					if (fieldName == 'conditions'){
						conditions = parser.getText();
					}
					else if (fieldName == 'visibility'){
						visibility = parser.getDecimalValue();
					}
					else if (fieldName == 'dew'){
						dew = parser.getDecimalValue();
					}
					else if (fieldName == 'sunrise'){
						sunrise = parser.getDateTimeValue();
					}
					else if (fieldName == 'sunset'){
						sunset = parser.getDateTimeValue();
					}
					else if (fieldName == 'wdir'){
						wdir = parser.getIntegerValue();
					}
					else if (fieldName == 'temp'){
						temp = parser.getDecimalValue();
					}
					else if (fieldName == 'wspd'){
						wspd = parser.getDecimalValue();
					}
					else if (fieldName == 'datetimeStr'){
						datetimeStr = parser.getText();
					}
					else if (fieldName == 'cloudcover'){
						cloudcover = parser.getDecimalValue();
					}
					else if (fieldName == 'heatindex'){
						heatindex = parser.getDecimalValue();
					}
					else if (fieldName == 'pop'){
						pop = parser.getIntegerValue ();
					}
					else if (fieldName == 'precip'){
						precip = parser.getDecimalValue ();
					}
					else if (fieldName == 'sealevelpressure'){
						sealevelpressure = parser.getDecimalValue();
					}
					else if (fieldName == 'snowdepth'){
						snowdepth = parser.getDecimalValue();
					}
					else if (fieldName == 'humidity'){
						humidity = parser.getDecimalValue  ();
					}
					else if (fieldName == 'wgust'){
						wgust = parser.getDecimalValue ();
					}
					else if (fieldName == 'windchill'){
						windchill = parser.getDecimalValue();
					}
				}
			}
		}
	}
    
    public Forecast_Entry__c convertToEntry(Location__c loc){
        return new Forecast_Entry__c(
             Air_Pressure__c = sealevelpressure,
              Time__c = DateTime.parse(datetimeStr).time(),
              Date__c = DateTime.parse(datetimeStr).date(),
              Humidity__c = humidity,
              Sunrise__c = sunrise.time(),
              Sunset__c = sunset.time(),
              Temperature__c = temp,
              Wind_Heading__c = wdir,
              Wind_Speed__c = wspd		 
        );
        
        
            
            /*
    Location__c
    Low__c
    Feels_Like__c
    High__c = 
	
	public String conditions {get;set;}
	public Decimal visibility {get;set;}
	public Decimal dew {get;set;}
	public String datetimeStr {get;set;}
	public Decimal cloudcover {get;set;}
	public Decimal heatindex {get;set;}
	public Integer pop {get;set;}
	public Decimal precip {get;set;}
	public Decimal snowdepth {get;set;}
	public Decimal wgust {get;set;}
	public Decimal windchill {get;set;}
*/

    }
}